name: leafscope
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  image_picker: ^1.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3   # <-- added

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png               # <-- your 1024x1024 PNG

flutter_launcher_icons:
  image_path: "assets/icon.png"
  android: true
  ios: false
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/icon.png"
